/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

public class IMEI extends TBCDSTRING {

	private static final long serialVersionUID = 1L;

	public IMEI() {
	}

	public IMEI(byte[] value) {
		super(value);
	}

}
