/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class IPBinaryAddress implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private IPBinV4Address iPBinV4Address = null;
	private IPBinV6AddressWithOrWithoutPrefixLength iPBinV6Address = null;
	
	public IPBinaryAddress() {
	}

	public IPBinaryAddress(byte[] code) {
		this.code = code;
	}

	public void setIPBinV4Address(IPBinV4Address iPBinV4Address) {
		this.iPBinV4Address = iPBinV4Address;
	}

	public IPBinV4Address getIPBinV4Address() {
		return iPBinV4Address;
	}

	public void setIPBinV6Address(IPBinV6AddressWithOrWithoutPrefixLength iPBinV6Address) {
		this.iPBinV6Address = iPBinV6Address;
	}

	public IPBinV6AddressWithOrWithoutPrefixLength getIPBinV6Address() {
		return iPBinV6Address;
	}

	public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (iPBinV6Address != null) {
			codeLength += iPBinV6Address.encode(reverseOS);
			return codeLength;
		}
		
		if (iPBinV4Address != null) {
			codeLength += iPBinV4Address.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 0
			reverseOS.write(0x80);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			iPBinV4Address = new IPBinV4Address();
			codeLength += iPBinV4Address.decode(is, false);
			return codeLength;
		}

		iPBinV6Address = new IPBinV6AddressWithOrWithoutPrefixLength();
		int choiceDecodeLength = iPBinV6Address.decode(is, berTag);
		if (choiceDecodeLength != 0) {
			return codeLength + choiceDecodeLength;
		}
		else {
			iPBinV6Address = null;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (iPBinV4Address != null) {
			sb.append("iPBinV4Address: ").append(iPBinV4Address);
			return;
		}

		if (iPBinV6Address != null) {
			sb.append("iPBinV6Address: ");
			iPBinV6Address.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

