/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class IPBinV6AddressWithOrWithoutPrefixLength implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private IPBinV6Address iPBinV6Address = null;
	private IPBinV6AddressWithPrefixLength iPBinV6AddressWithPrefix = null;
	
	public IPBinV6AddressWithOrWithoutPrefixLength() {
	}

	public IPBinV6AddressWithOrWithoutPrefixLength(byte[] code) {
		this.code = code;
	}

	public void setIPBinV6Address(IPBinV6Address iPBinV6Address) {
		this.iPBinV6Address = iPBinV6Address;
	}

	public IPBinV6Address getIPBinV6Address() {
		return iPBinV6Address;
	}

	public void setIPBinV6AddressWithPrefix(IPBinV6AddressWithPrefixLength iPBinV6AddressWithPrefix) {
		this.iPBinV6AddressWithPrefix = iPBinV6AddressWithPrefix;
	}

	public IPBinV6AddressWithPrefixLength getIPBinV6AddressWithPrefix() {
		return iPBinV6AddressWithPrefix;
	}

	public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (iPBinV6AddressWithPrefix != null) {
			codeLength += iPBinV6AddressWithPrefix.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 4
			reverseOS.write(0xA4);
			codeLength += 1;
			return codeLength;
		}
		
		if (iPBinV6Address != null) {
			codeLength += iPBinV6Address.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			reverseOS.write(0x81);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			iPBinV6Address = new IPBinV6Address();
			codeLength += iPBinV6Address.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 4)) {
			iPBinV6AddressWithPrefix = new IPBinV6AddressWithPrefixLength();
			codeLength += iPBinV6AddressWithPrefix.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (iPBinV6Address != null) {
			sb.append("iPBinV6Address: ").append(iPBinV6Address);
			return;
		}

		if (iPBinV6AddressWithPrefix != null) {
			sb.append("iPBinV6AddressWithPrefix: ");
			iPBinV6AddressWithPrefix.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

