/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class LevelOfCAMELService extends BerBitString {

	private static final long serialVersionUID = 1L;

	public LevelOfCAMELService() {
	}

	public LevelOfCAMELService(byte[] code) {
		super(code);
	}

	public LevelOfCAMELService(byte[] value, int numBits) {
		super(value, numBits);
	}

	public LevelOfCAMELService(boolean[] value) {
		super(value);
	}

}
