/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class MessageReference extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public MessageReference() {
	}

	public MessageReference(byte[] value) {
		super(value);
	}

}
