/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class NetworkInitiatedPDPContext extends BerBoolean {

	private static final long serialVersionUID = 1L;

	public NetworkInitiatedPDPContext() {
	}

	public NetworkInitiatedPDPContext(byte[] code) {
		super(code);
	}

	public NetworkInitiatedPDPContext(boolean value) {
		super(value);
	}

}
