/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class PDPAddress implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private IPAddress iPAddress = null;
	private ETSIAddress eTSIAddress = null;
	
	public PDPAddress() {
	}

	public PDPAddress(byte[] code) {
		this.code = code;
	}

	public void setIPAddress(IPAddress iPAddress) {
		this.iPAddress = iPAddress;
	}

	public IPAddress getIPAddress() {
		return iPAddress;
	}

	public void setETSIAddress(ETSIAddress eTSIAddress) {
		this.eTSIAddress = eTSIAddress;
	}

	public ETSIAddress getETSIAddress() {
		return eTSIAddress;
	}

	public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		int sublength;

		if (eTSIAddress != null) {
			codeLength += eTSIAddress.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			reverseOS.write(0x81);
			codeLength += 1;
			return codeLength;
		}
		
		if (iPAddress != null) {
			sublength = iPAddress.encode(reverseOS);
			codeLength += sublength;
			codeLength += BerLength.encodeLength(reverseOS, sublength);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 0
			reverseOS.write(0xA0);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 0)) {
			codeLength += BerLength.skip(is);
			iPAddress = new IPAddress();
			codeLength += iPAddress.decode(is, null);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			eTSIAddress = new ETSIAddress();
			codeLength += eTSIAddress.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (iPAddress != null) {
			sb.append("iPAddress: ");
			iPAddress.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (eTSIAddress != null) {
			sb.append("eTSIAddress: ").append(eTSIAddress);
			return;
		}

		sb.append("<none>");
	}

}

