/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package com.bd.asn.zte.data.pgw_r8_new;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.math.BigInteger;


public class ServiceChargeType extends BerEnum {

	private static final long serialVersionUID = 1L;

	public ServiceChargeType() {
	}

	public ServiceChargeType(byte[] code) {
		super(code);
	}

	public ServiceChargeType(BigInteger value) {
		super(value);
	}

	public ServiceChargeType(long value) {
		super(value);
	}

}
