spring:
  application:
    name: file-scanner-service
  
  # Use H2 in-memory database for testing Swagger
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  
  liquibase:
    enabled: false
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
  
  quartz:
    job-store-type: memory

server:
  port: 8081
  servlet:
    context-path: /file-scanner

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true
  packages-to-scan: com.quantumsoft.tia.scanner.controllers
  paths-to-match: /**

scanner:
  instance-id: ${HOSTNAME:scanner-1}
  scan:
    default-timeout: 5m
    max-concurrent-scans: 3
    file-size-limit: 1024MB
  queue:
    batch-size: 100
    lock-timeout: 5m
    cleanup-interval: 1h
  metrics:
    enabled: true
    collection-interval: 30s

logging:
  level:
    com.quantumsoft.tia.scanner: DEBUG
    org.springframework.web: INFO