name: ZTE Parser Library - Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'parsers/zte-asn1-parser/**'
    tags:
      - 'zte-parser-v*'
  pull_request:
    branches:
      - main
    paths:
      - 'parsers/zte-asn1-parser/**'
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch, minor, major)'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build-and-test:
    name: Build and Test ZTE Parser Library
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build core parser-api first
        run: ./gradlew :core:parser-api:build --no-daemon

      - name: Build zte-asn1-parser library
        run: ./gradlew :parsers:zte-asn1-parser:build --no-daemon

      - name: Run zte-asn1-parser tests
        run: ./gradlew :parsers:zte-asn1-parser:test --no-daemon

      - name: Run integration tests
        run: ./gradlew :parsers:zte-asn1-parser:integrationTest --no-daemon
        continue-on-error: true

      - name: Generate test report
        run: ./gradlew :parsers:zte-asn1-parser:jacocoTestReport --no-daemon
        if: always()

      - name: Run quality checks
        run: ./gradlew :parsers:zte-asn1-parser:qualityCheck --no-daemon
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zte-parser-test-results
          path: parsers/zte-asn1-parser/build/test-results/test/
          retention-days: 30

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zte-parser-test-report
          path: parsers/zte-asn1-parser/build/reports/tests/test/
          retention-days: 30

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zte-parser-coverage-report
          path: parsers/zte-asn1-parser/build/reports/jacoco/test/html/
          retention-days: 30

      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zte-parser-security-report
          path: parsers/zte-asn1-parser/build/reports/dependency-check-report.html
          retention-days: 30

      - name: Verify JAR creation
        run: ./gradlew :parsers:zte-asn1-parser:jar :parsers:zte-asn1-parser:sourcesJar :parsers:zte-asn1-parser:javadocJar --no-daemon

      - name: Create executable JAR for deployment
        run: ./gradlew :parsers:zte-asn1-parser:bootJar --no-daemon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zte-parser-jars
          path: parsers/zte-asn1-parser/build/libs/
          retention-days: 30

  semantic-version:
    name: Calculate Semantic Version
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    outputs:
      version: ${{ steps.semantic.outputs.version }}
      tag: ${{ steps.semantic.outputs.tag }}
      changelog: ${{ steps.semantic.outputs.changelog }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate semantic version
        id: semantic
        run: |
          # Get the latest tag for zte-parser
          LATEST_TAG=$(git tag -l "zte-parser-v*" --sort=-version:refname | head -n1)
          
          if [ -z "$LATEST_TAG" ]; then
            # No existing tags, start with 1.0.0
            NEW_VERSION="1.0.0"
          else
            # Extract version number from tag (e.g., zte-parser-v1.2.3 -> 1.2.3)
            CURRENT_VERSION=$(echo "$LATEST_TAG" | sed 's/zte-parser-v//')
            
            # Parse version components
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            
            # Determine version bump based on commit messages since last tag
            COMMITS=$(git log ${LATEST_TAG}..HEAD --oneline --grep="BREAKING CHANGE" --grep="feat:" --grep="fix:" -- parsers/zte-asn1-parser/)
            
            if echo "$COMMITS" | grep -q "BREAKING CHANGE"; then
              # Major version bump for breaking changes
              NEW_VERSION="$((MAJOR + 1)).0.0"
            elif echo "$COMMITS" | grep -q "feat:"; then
              # Minor version bump for new features
              NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
            elif echo "$COMMITS" | grep -q "fix:"; then
              # Patch version bump for bug fixes
              NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
            else
              # Default to patch bump if changes exist
              if [ -n "$COMMITS" ]; then
                NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
              else
                NEW_VERSION="$CURRENT_VERSION"
              fi
            fi
          fi
          
          # Manual version bump from workflow dispatch
          if [ "${{ github.event.inputs.version_bump }}" != "" ]; then
            IFS='.' read -r MAJOR MINOR PATCH <<< "$NEW_VERSION"
            case "${{ github.event.inputs.version_bump }}" in
              "major") NEW_VERSION="$((MAJOR + 1)).0.0" ;;
              "minor") NEW_VERSION="$MAJOR.$((MINOR + 1)).0" ;;
              "patch") NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))" ;;
            esac
          fi
          
          TAG="zte-parser-v$NEW_VERSION"
          
          # Generate changelog
          if [ -n "$LATEST_TAG" ]; then
            CHANGELOG=$(git log ${LATEST_TAG}..HEAD --pretty=format:"- %s" --no-merges -- parsers/zte-asn1-parser/)
          else
            CHANGELOG=$(git log --pretty=format:"- %s" --no-merges -- parsers/zte-asn1-parser/)
          fi
          
          # Use multiline output for changelog
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          
          echo "Calculated version: $NEW_VERSION"
          echo "Tag: $TAG"

  publish:
    name: Publish ZTE Parser Library
    runs-on: ubuntu-latest
    needs: [build-and-test, semantic-version]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build core parser-api dependency
        run: ./gradlew :core:parser-api:build --no-daemon

      - name: Set version in gradle.properties
        run: |
          echo "version=${{ needs.semantic-version.outputs.version }}" > parsers/zte-asn1-parser/gradle.properties

      - name: Build with new version
        run: ./gradlew :parsers:zte-asn1-parser:releaseBuild --no-daemon
        env:
          ORG_GRADLE_PROJECT_version: ${{ needs.semantic-version.outputs.version }}

      - name: Publish to GitHub Packages
        run: ./gradlew :parsers:zte-asn1-parser:publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          ORG_GRADLE_PROJECT_version: ${{ needs.semantic-version.outputs.version }}

      - name: Create deployment package
        run: ./gradlew :parsers:zte-asn1-parser:deploymentPackage --no-daemon
        env:
          ORG_GRADLE_PROJECT_version: ${{ needs.semantic-version.outputs.version }}

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: zte-parser-deployment-package
          path: parsers/zte-asn1-parser/build/deployment/
          retention-days: 90

      - name: Create Git tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ needs.semantic-version.outputs.tag }}" -m "Release zte-asn1-parser v${{ needs.semantic-version.outputs.version }}"
          git push origin "${{ needs.semantic-version.outputs.tag }}"

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.semantic-version.outputs.tag }}
          name: ZTE ASN.1 Parser Library v${{ needs.semantic-version.outputs.version }}
          body: |
            ## ZTE ASN.1 Parser Library v${{ needs.semantic-version.outputs.version }}
            
            A Kotlin library for parsing ZTE ZXUN CG ASN.1 encoded CDR files. This library can be used as a Gradle dependency in other projects or deployed as a standalone parser plugin.
            
            ### Changes
            ${{ needs.semantic-version.outputs.changelog }}
            
            ### Usage as Gradle Dependency
            Add this dependency to your `build.gradle.kts`:
            
            ```kotlin
            dependencies {
                implementation("com.quantumsoft.tia.parsers:zte-asn1-parser:${{ needs.semantic-version.outputs.version }}")
            }
            ```
            
            ### Maven Repository Configuration
            ```kotlin
            repositories {
                maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/quantum-soft-dev/tia-etl-system")
                    credentials {
                        username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                        password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
                    }
                }
            }
            ```
            
            ### Parser Plugin Deployment
            For deploying as a parser plugin:
            1. Download the deployment package from this release
            2. Extract to `/opt/tia/parsers/zte-asn1-parser/`
            3. Register the parser using the included metadata.json
            
            ### Features
            - ASN.1 CDR file parsing with JASN.1 library
            - Support for multiple ZTE record types (PGW, SGW, etc.)
            - ClickHouse batch loading optimizations
            - Comprehensive validation and error handling
            - Spring Boot integration with metrics and monitoring
            
            ### Authentication for GitHub Packages
            To access GitHub Packages, create a Personal Access Token with `read:packages` permission:
            
            1. Go to GitHub → Settings → Developer settings → Personal access tokens
            2. Create token with `read:packages` scope
            3. Configure in your project:
               - `gpr.user`: your GitHub username
               - `gpr.key`: your personal access token
               
            Or set environment variables:
            - `USERNAME`: your GitHub username
            - `TOKEN`: your personal access token
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            parsers/zte-asn1-parser/build/libs/zte-asn1-parser-${{ needs.semantic-version.outputs.version }}.jar
            parsers/zte-asn1-parser/build/libs/zte-asn1-parser-${{ needs.semantic-version.outputs.version }}-sources.jar
            parsers/zte-asn1-parser/build/libs/zte-asn1-parser-${{ needs.semantic-version.outputs.version }}-javadoc.jar
            parsers/zte-asn1-parser/build/libs/zte-asn1-parser-${{ needs.semantic-version.outputs.version }}-executable.jar
            parsers/zte-asn1-parser/build/deployment/metadata.json